### ISSUE TITLE
Issue: Sky Scrapper API

### ISSUE THREAD

**Issue by CS9490** [CS9490/Travel-Itinerary-Project#23]
# BUG WITH SKY SCRAPPER API

## Estimate: 3 days

Hi all,
Please take a look into the Sky Scrapper API. I have paid for a key (to make our lives easier when it comes to testing/creating...), but the API key is incredibly buggy. Sometimes the filters are input as intended in the application, and sometimes they are not. Funnily enough once I change the account and make a new free API key, it tends to work in the beginning and then ends up not working, despite not having run out of free uses. 

![API Key Working](https://github.com/CS9490/Travel-Itinerary-Project/assets/135974225/aa87eefa-067b-4661-89ce-64d456ee2026)

Here you can see that the Query Parameters work as intended, as set up in our view.py and flights.py file, however, on the paid API key, after a couple uses, I get the following, along with an error shown here:

Query Parameters are missing:
![API Key Not Working Missing Parameters](https://github.com/CS9490/Travel-Itinerary-Project/assets/135974225/8f3837f1-f787-47f1-84d2-742255d703c0)

The API Key doesn't returns a None object, causing the website to crash - possibly need to set up a better try-catch method for this:

<img width="1258" alt="None Object Returned" src="https://github.com/CS9490/Travel-Itinerary-Project/assets/135974225/f1cc6493-292a-4957-a992-3e7562ff44e7">

@mohammedfahadnyc you mentioned that the key was the culprit of this in the past, but I attempted a cURL test and got results using my paid key. Please take a look at the code you provided for the flights.py file and see if you can figure this part out - reach out if there is anything we can assist you with, and please reach out for me to provide you with the key.

Here is the cURL test I mentioned doing to show that my API key does return values:
<img width="1180" alt="cURL working" src="https://github.com/CS9490/Travel-Itinerary-Project/assets/135974225/318ef007-d4cf-4d68-aa33-ea9e3a29ac57">

Here is the curl command I used: curl -X GET 'https://api.yelp.com/v3/businesses/search?location=San%20Francisco' -H 'Authorization: Bearer [apikey]'

Once again, please reach out to me personally for the API key I bought.

**Comment by CS9490** [comment]
As per the review in our last sprint meeting, the bug has been fixed.

**Comment by CS9490** [comment]
The API still at times refuses to return certain information for valid flight times. Most Western European cities work, but many cities from other countries seem to cause it to fail: initially it returns no information in the search_results, and then if you run it again, the error begins appearing and doesn't stop appearing.

**Comment by mohammedfahadnyc** [comment]
Issue has been resolved.
